# Challenge 1 - Tic Tac Toe

In this lab you will perform deep learning analysis on a dataset of playing [Tic Tac Toe](https://en.wikipedia.org/wiki/Tic-tac-toe).

There are 9 grids in Tic Tac Toe that are coded as the following picture shows:

![Tic Tac Toe Grids](https://github.com/kerondavid-debug/lab-neural-networks/blob/master/your-code/tttboard.jpg?raw=1)

In the first 9 columns of the dataset you can find which marks (`x` or `o`) exist in the grids. If there is no mark in a certain grid, it is labeled as `b`. The last column is `class` which tells you whether Player X (who always moves first in Tic Tac Toe) wins in this configuration. Note that when `class` has the value `False`, it means either Player O wins the game or it ends up as a draw.

Follow the steps suggested below to conduct a neural network analysis using Tensorflow and Keras. You will build a deep learning model to predict whether Player X wins the game or not.

## Step 1: Data Engineering

This dataset is almost in the ready-to-use state so you do not need to worry about missing values and so on. Still, some simple data engineering is needed.

1. Read `tic-tac-toe.csv` into a dataframe.
1. Inspect the dataset. Determine if the dataset is reliable by eyeballing the data.
1. Convert the categorical values to numeric in all columns.
1. Separate the inputs and output.
1. Normalize the input data.

In [125]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from tensorflow import keras
from tensorflow.keras import layers

In [126]:
df = pd.read_csv('/content/tic-tac-toe.csv')

In [127]:
# Inspecting data
df.shape

(958, 10)

In [128]:
df.dtypes

TL       object
TM       object
TR       object
ML       object
MM       object
MR       object
BL       object
BM       object
BR       object
class      bool
dtype: object

In [129]:
df.head()

  TL TM TR ML MM MR BL BM BR  class
0  x  x  x  x  o  o  x  o  o   True
1  x  x  x  x  o  o  o  x  o   True
2  x  x  x  x  o  o  o  o  x   True
3  x  x  x  x  o  o  o  b  b   True
4  x  x  x  x  o  o  b  o  b   True

In [130]:
from sklearn.preprocessing import LabelEncoder

for col in df.columns:
  le = LabelEncoder()
  df[col] = le.fit_transform(df[col])

In [131]:
X = df.drop("class", axis=1)
Y = df["class"]

In [132]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X = scaler.fit_transform(X)

## Step 2: Build Neural Network

To build the neural network, you can refer to your own codes you wrote while following the [Deep Learning with Python, TensorFlow, and Keras tutorial](https://www.youtube.com/watch?v=wQ8BIBpya2k) in the lesson. It's pretty similar to what you will be doing in this lab.

1. Split the training and test data.
1. Create a `Sequential` model.
1. Add several layers to your model. Make sure you use ReLU as the activation function for the middle layers. Use Softmax for the output layer because each output has a single lable and all the label probabilities add up to 1.
1. Compile the model using `adam` as the optimizer and `sparse_categorical_crossentropy` as the loss function. For metrics, use `accuracy` for now.
1. Fit the training data.
1. Evaluate your neural network model with the test data.
1. Save your model as `tic-tac-toe.model`.

In [133]:
# Splitting
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

In [134]:
# Model building
model = keras.Sequential([
    layers.Dense(64, activation='relu', input_shape=(9,)),
    layers.Dense(32, activation='relu'),
    layers.Dense(2, activation='softmax')
])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [135]:
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

In [136]:

model.fit(X_train, y_train, epochs=10, batch_size=32, validation_split=0.2)

Epoch 1/10
20/20 ━━━━━━━━━━━━━━━━━━━━ 3s 60ms/step - accuracy: 0.6340 - loss: 0.6494 - val_accuracy: 0.6818 - val_loss: 0.6353
Epoch 2/10
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6699 - loss: 0.6068 - val_accuracy: 0.6948 - val_loss: 0.6230
Epoch 3/10
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7141 - loss: 0.5857 - val_accuracy: 0.7208 - val_loss: 0.6226
Epoch 4/10
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7206 - loss: 0.5701 - val_accuracy: 0.7273 - val_loss: 0.6110
Epoch 5/10
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7320 - loss: 0.5540 - val_accuracy: 0.7338 - val_loss: 0.6067
Epoch 6/10
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7320 - loss: 0.5395 - val_accuracy: 0.7597 - val_loss: 0.5948
Epoch 7/10
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7549 - loss: 0.5249 - val_accuracy: 0.7338 - val_loss: 0.5887
Epoch 8/10
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7729 - loss: 0.5074 - val_accuracy: 0.7662 - val_loss: 0.5769
Epoch 9/10
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7761 - loss: 0.4935 - val_accuracy: 0.7532 - val_loss: 0.5680
Epoch 10/10
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7990 - loss: 0.4751 - val_accuracy: 0.7727 - val_loss: 0.5511

In [137]:
model.save("tic-tac-toe.keras")

## Step 3: Make Predictions

Now load your saved model and use it to make predictions on a few random rows in the test dataset. Check if the predictions are correct.

In [138]:


# Select a few random rows from X_test
num_predictions = 5
random_indices = np.random.choice(X_test.shape[0], num_predictions, replace=False)
sample_X_test = X_test[random_indices]
sample_y_test = y_test.iloc[random_indices]

# Make predictions
# model.predict returns probabilities for each class
predictions_proba = model.predict(sample_X_test)
predicted_classes = np.argmax(predictions_proba, axis=1) # Get the class with the highest probability

print(f"\nRandom sample from X_test (scaled):\n{sample_X_test}")
print(f"\nTrue labels for the sample:\n{sample_y_test.values}")
print(f"\nPredicted probabilities for the sample:\n{predictions_proba}")
print(f"\nPredicted classes for the sample:\n{predicted_classes}")

# Compare true labels with predicted classes
comparison = pd.DataFrame({
    'True_Label': sample_y_test.values,
    'Predicted_Class': predicted_classes,
    'Correct_Prediction': (sample_y_test.values == predicted_classes)
})
print("\nComparison of True vs. Predicted Classes:")
display(comparison)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 200ms/step

Random sample from X_test (scaled):
[[ 1.00322257  1.08495342 -0.28682739  1.08495342 -0.42007679 -1.41958965
  -0.28682739 -0.16731812  1.00322257]
 [-1.57687736  1.08495342 -1.57687736 -0.16731812 -0.42007679 -0.16731812
   1.00322257 -1.41958965  1.00322257]
 [-0.28682739  1.08495342  1.00322257 -0.16731812  0.93037142  1.08495342
  -0.28682739 -1.41958965 -0.28682739]
 [-0.28682739 -1.41958965 -0.28682739  1.08495342  0.93037142  1.08495342
  -1.57687736 -1.41958965 -1.57687736]
 [-0.28682739 -1.41958965  1.00322257 -0.16731812 -1.770525    1.08495342
   1.00322257 -0.16731812  1.00322257]]

True labels for the sample:
[0 0 0 1 1]

Predicted probabilities for the sample:
[[0.36349273 0.63650733]
 [0.69292456 0.3070754 ]
 [0.18834373 0.8116563 ]
 [0.12602696 0.873973  ]
 [0.21321635 0.78678364]]

Predicted classes for the sample:
[1 0 1 1 1]

Comparison of True vs. Predicted Classes:

   True_Label  Predicted_Class  Correct_Prediction
0           0                1               False
1           0                0                True
2           0                1               False
3           1                1                True
4           1                1                True

## Step 4: Improve Your Model

Did your model achieve low loss (<0.1) and high accuracy (>0.95)? If not, try to improve your model.

But how? There are so many things you can play with in Tensorflow and in the next challenge you'll learn about these things. But in this challenge, let's just do a few things to see if they will help.

* Add more layers to your model. If the data are complex you need more layers. But don't use more layers than you need. If adding more layers does not improve the model performance you don't need additional layers.
* Adjust the learning rate when you compile the model. This means you will create a custom `tf.keras.optimizers.Adam` instance where you specify the learning rate you want. Then pass the instance to `model.compile` as the optimizer.
    * `tf.keras.optimizers.Adam` [reference](https://www.tensorflow.org/api_docs/python/tf/keras/optimizers/Adam).
    * Don't worry if you don't understand what the learning rate does. You'll learn about it in the next challenge.
* Adjust the number of epochs when you fit the training data to the model. Your model performance continues to improve as you train more epochs. But eventually it will reach the ceiling and the performance will stay the same.

### Step 4: Improving the Model

I will attempt to improve the model by:
1. Adding an additional dense layer.
2. Specifying a custom learning rate for the Adam optimizer.
3. Increasing the number of epochs for training.

In [139]:
print("\n--- Step 4: Improve Your Model ---")

# Model building with additional layers
model_improved = keras.Sequential([
    layers.Dense(128, activation='relu', input_shape=(9,)), # Increased neurons
    layers.Dense(64, activation='relu'),
    layers.Dense(32, activation='relu'), # Added another layer
    layers.Dense(2, activation='softmax')
])

--- Step 4: Improve Your Model ---

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [140]:
# Adjusting the learning rate
custom_adam = keras.optimizers.Adam(learning_rate=0.001) # Example learning rate

model_improved.compile(optimizer=custom_adam, loss='sparse_categorical_crossentropy', metrics=['accuracy'])

In [141]:
# Fitting the improved model with more epochs
print("\nTraining the improved model...")
model_improved.fit(X_train, y_train, epochs=20, batch_size=32, validation_split=0.2)

Training the improved model...
Epoch 1/20
20/20 ━━━━━━━━━━━━━━━━━━━━ 3s 79ms/step - accuracy: 0.6405 - loss: 0.6417 - val_accuracy: 0.6883 - val_loss: 0.6038
Epoch 2/20
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6846 - loss: 0.5790 - val_accuracy: 0.7403 - val_loss: 0.5881
Epoch 3/20
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7271 - loss: 0.5427 - val_accuracy: 0.7208 - val_loss: 0.5815
Epoch 4/20
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7843 - loss: 0.5006 - val_accuracy: 0.7662 - val_loss: 0.5687
Epoch 5/20
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8105 - loss: 0.4570 - val_accuracy: 0.7597 - val_loss: 0.5386
Epoch 6/20
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8366 - loss: 0.4158 - val_accuracy: 0.7727 - val_loss: 0.5060
Epoch 7/20
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8497 - loss: 0.3757 - val_accuracy: 0.7922 - val_loss: 0.4724
Epoch 8/20
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8775 - loss: 0.3481 - val_accuracy: 0.8182 - val_loss: 0.4438
Epoch 9/20
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8840 - loss: 0.3235 - val_accuracy: 0.8377 - val_loss: 0.4367
Epoch 10/20
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9003 - loss: 0.2807 - val_accuracy: 0.8442 - val_loss: 0.4071
Epoch 11/20
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9216 - loss: 0.2561 - val_accuracy: 0.8182 - val_loss: 0.4004
Epoch 12/20
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9346 - loss: 0.2221 - val_accuracy: 0.8506 - val_loss: 0.3618
Epoch 13/20
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9379 - loss: 0.1917 - val_accuracy: 0.8701 - val_loss: 0.3387
Epoch 14/20
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9493 - loss: 0.1691 - val_accuracy: 0.8636 - val_loss: 0.3266
Epoch 15/20
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9575 - loss: 0.1531 - val_accuracy: 0.8831 - val_loss: 0.3068
Epoch 16/20
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9690 - loss: 0.1249 - val_accuracy: 0.8701 - val_loss: 0.2914
Epoch 17/20
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9673 - loss: 0.1180 - val_accuracy: 0.8831 - val_loss: 0.2811
Epoch 18/20
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9771 - loss: 0.0928 - val_accuracy: 0.8831 - val_loss: 0.2704
Epoch 19/20
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9902 - loss: 0.0724 - val_accuracy: 0.8961 - val_loss: 0.2552
Epoch 20/20
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9918 - loss: 0.0684 - val_accuracy: 0.9026 - val_loss: 0.2588

In [142]:
# Evaluate the improved model
loss, accuracy = model_improved.evaluate(X_test, y_test)
print(f"\nImproved Model Test Loss: {loss:.4f}")
print(f"Improved Model Test Accuracy: {accuracy:.4f}")

6/6 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8958 - loss: 0.2405

Improved Model Test Loss: 0.2405
Improved Model Test Accuracy: 0.8958

Now, let's make predictions with the improved model to see if the predictions are more accurate.

In [143]:
# Make predictions with the improved model

# Select a few random rows from X_test
num_predictions = 5
random_indices = np.random.choice(X_test.shape[0], num_predictions, replace=False)
sample_X_test = X_test[random_indices]
sample_y_test = y_test.iloc[random_indices]

predictions_proba_improved = model_improved.predict(sample_X_test)
predicted_classes_improved = np.argmax(predictions_proba_improved, axis=1)

print(f"\nRandom sample from X_test (scaled):\n{sample_X_test}")
print(f"\nTrue labels for the sample:\n{sample_y_test.values}")
print(f"\nPredicted probabilities (Improved Model):\n{predictions_proba_improved}")
print(f"\nPredicted classes (Improved Model):\n{predicted_classes_improved}")

comparison_improved = pd.DataFrame({
    'True_Label': sample_y_test.values,
    'Predicted_Class_Improved': predicted_classes_improved,
    'Correct_Prediction': (sample_y_test.values == predicted_classes_improved)
})
print("\nComparison of True vs. Predicted Classes (Improved Model):")
display(comparison_improved)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 419ms/step

Random sample from X_test (scaled):
[[ 1.00322257  1.08495342 -0.28682739  1.08495342  0.93037142 -0.16731812
  -0.28682739 -0.16731812  1.00322257]
 [ 1.00322257 -1.41958965  1.00322257 -1.41958965 -1.770525    1.08495342
  -0.28682739 -0.16731812 -0.28682739]
 [-1.57687736 -0.16731812 -1.57687736  1.08495342  0.93037142  1.08495342
  -0.28682739 -0.16731812  1.00322257]
 [ 1.00322257 -0.16731812  1.00322257 -1.41958965  0.93037142 -1.41958965
  -0.28682739 -0.16731812  1.00322257]
 [ 1.00322257 -0.16731812 -1.57687736 -1.41958965 -0.42007679  1.08495342
  -1.57687736 -0.16731812  1.00322257]]

True labels for the sample:
[1 0 1 1 0]

Predicted probabilities (Improved Model):
[[2.6625437e-01 7.3374563e-01]
 [9.4033331e-01 5.9666764e-02]
 [1.6977055e-01 8.3022940e-01]
 [1.9882619e-02 9.8011738e-01]
 [9.9904293e-01 9.5699023e-04]]

Predicted classes (Improved Model):
[1 0 1 1 0]

Comparison of True vs. Predicted Classes (Improved Model):

   True_Label  Predicted_Class_Improved  Correct_Prediction
0           1                         1                True
1           0                         0                True
2           1                         1                True
3           1                         1                True
4           0                         0                True

**Which approach(es) did you find helpful to improve your model performance?**